#!/usr/bin/env python3
"""Generate the full-product inventory; never infer a scientific benchmark freeze."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[2]


def full_product(path: Path) -> dict | None:
    record = json.loads(path.read_text(encoding="utf-8"))
    selection = record.get("selection")
    if selection != "full" and not (
        not selection and "full" in path.stem.split("_")
    ):
        return None
    stats = record.get("stats", record)
    product = record.get("product_id") or path.parent.name
    kind = str(record.get("kind", stats.get("kind", "")))
    unit = record.get("unit")
    # Older stats lack unit/kind. Product identifiers distinguish their populations.
    hints = f"{product} {kind}".lower()
    if not unit:
        if any(term in hints for term in ("phase", "pick", "arrival")):
            unit = "phase_pick"
        elif any(term in hints for term in ("focal", "mechanism", "moment_tensor")):
            unit = "focal_mechanism"
        elif "absolute_approx" in hints:
            unit = "approximate_event"
        elif "relative" in hints:
            unit = "relative_event"
        elif "row_count" in stats and (
            "ranges" in stats or "event" in hints or "origin" in hints
        ):
            unit = "event"
        else:
            unit = "unknown"
    count = stats.get("row_count", stats.get("phase_rows"))
    return {"product": product, "unit": unit, "count": count, "path": path}


def catalog_status(products: list[dict]) -> str:
    if any(
        p["unit"] in {"event", "relative_event"}
        and isinstance(p["count"], int) and p["count"] > 0
        for p in products
    ):
        return "ready"
    return "partial" if products else "missing"


def window_status(case: Path) -> str:
    config = case / "analysis/processing.yaml"
    if not config.exists():
        return "unknown"
    match = re.search(r"^window_status:\s*([\w-]+)", config.read_text(), re.M)
    return match[1] if match else "unknown"


def build_manifest(data: Path) -> str:
    def link(path: Path) -> str:
        return "./" + quote(path.relative_to(data).as_posix(), safe="/")

    cases = sorted(p for p in data.iterdir() if (p / "catalogs").is_dir())
    inventory = {}
    for case in cases:
        catalogs = []
        for catalog in sorted(p for p in (case / "catalogs").iterdir() if p.is_dir()):
            products = []
            for path in sorted((catalog / "analysis/stats").rglob("*.json")):
                product = full_product(path)
                if product is not None:
                    products.append(product)
            catalogs.append((catalog, products, catalog_status(products)))
        inventory[case] = catalogs

    lines = [
        "# Catalog Analysis Manifest", "",
        "Generated by `scripts/04_catalog_analysis/build_catalog_manifest.py` from existing full-product statistics. No source catalogs are modified.", "",
        "## Interpretation", "",
        "- This is local product readiness, not scientific evaluation readiness. Current window status is read from each case's `analysis/processing.yaml`.",
        "- `ready`: at least one nonempty event or native relative-event full product has statistics; `partial`: only auxiliary/unknown/empty products; `missing`: no full-product statistics. Consult the catalog README for actual file availability and limitations.",
        "- Counts remain per product with explicit units; never add phase/pick rows, alternate versions, approximate coordinates or overlapping event populations together.",
        "- `operational_benchmark` is a separately acquired historical query snapshot. Its full row count does not mean the benchmark window is approved.",
        "- Existing masked statistics and figures are exploratory. They remain under each catalog's `analysis/`, not a second hand-maintained summary.", "",
        "## Case overview", "",
        "| Case | Catalogs | Ready | Partial | Missing | Window status |",
        "|---|---:|---:|---:|---:|---|",
    ]
    for case, catalogs in inventory.items():
        counts = {s: sum(status == s for _, _, status in catalogs)
                  for s in ("ready", "partial", "missing")}
        lines.append(
            f"| [{case.name}]({link(case)}) | {len(catalogs)} | {counts['ready']} | "
            f"{counts['partial']} | {counts['missing']} | `{window_status(case)}` |"
        )
    for case, catalogs in inventory.items():
        lines += ["", f"## `{case.name}`", ""]
        for catalog, products, status in catalogs:
            lines += [f"### [{catalog.name}]({link(catalog / 'README.md')}) — {status}", ""]
            analysis = catalog / "analysis/catalog_analysis.md"
            if analysis.exists():
                lines += [f"[Generated processing report]({link(analysis)})", ""]
            figures = catalog / "analysis/figures"
            if figures.exists():
                lines += [f"[Exploratory figures]({link(figures)}/)", ""]
            if not products:
                lines += ["No full-product statistics; see the catalog README for the missing-product assessment.", ""]
                continue
            lines += ["| Product | Unit | Full rows | Statistics |", "|---|---|---:|---|"]
            for product in products:
                count = product["count"]
                formatted = f"{count:,}" if isinstance(count, int) else "—"
                lines.append(
                    f"| `{product['product']}` | `{product['unit']}` | {formatted} | "
                    f"[JSON]({link(product['path'])}) |"
                )
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--output", type=Path, help="Optional output path for a preview")
    args = parser.parse_args()
    data = args.root.resolve() / "data"
    output = args.output or data / "CATALOGS_MANIFEST.md"
    output.write_text(build_manifest(data), encoding="utf-8")


if __name__ == "__main__":
    main()
