"""HypoDD grid workflow: build ``hypoDD_*.inp``, run the binary per grid, merge catalogs and residuals.

Uses :class:`Run_HypoDD` with PyTorch :class:`~torch.utils.data.Dataset` for parallel grid jobs,
plus helpers to merge outputs and summarize relocation quality.
"""
import os, shutil, glob
from typing import Optional

import pandas as pd
from obspy import UTCDateTime
from torch.utils.data import Dataset

try:
    from .errors import InsufficientDTimeError, NativeOutputError
    from .native import run_native_program, read_log_tail
except ImportError:  # pragma: no cover - legacy direct-script execution
    from errors import InsufficientDTimeError, NativeOutputError
    from native import run_native_program, read_log_tail


def _fmt_layer_line(values):
    """Format one model layer row for ``hypoDD.inp`` (space-separated floats, newline-terminated).

    Parameters
    ----------
    values : sequence of float
        Layer top depths or velocities in HypoDD ``hypoDD.inp`` order.
    """
    return '  ' + '  '.join(f'{v:g}' for v in values) + '\n'


def write_hypodd_inp_programmatic(i, j, out_folder, cfg):
    """
    Write hypoDD control file following the line order expected by getinp.f
    (no dependency on substring matching in a template).

    For hypodd_idata in (1, 3), provide dt.cc via dt_{i}-{j}.cc (or ./dt.cc if
    hypodd_dt_cc_per_grid is False) before running HypoDD.

    Parameters
    ----------
    i, j : int
        Grid indices; filenames use the ``{i}-{j}`` suffix.
    out_folder : str
        Directory where ``hypoDD_{i}-{j}.inp`` is written.
    cfg : object
        Same attributes as :class:`config.Config` (hypodd_*, paths, ``hypodd_dt_cc_per_grid``).
    """
    idata = cfg.hypodd_idata
    cc_name = f'./dt_{i}-{j}.cc' if getattr(cfg, 'hypodd_dt_cc_per_grid', True) else './dt.cc'
    ct_name = f'./dt_{i}-{j}.ct'
    eve_name = f'./event_{i}-{j}.dat'
    sta_name = './hypoDD_station.dat'
    suffix = f'{i}-{j}'
    lines = []
    add = lines.append
    add('* hypoDD.inp generated by hypodd (order matches getinp.f)\n')
    add('*--- input files\n')
    add(f'{cc_name}\n')
    add(f'{ct_name}\n')
    add(f'{eve_name}\n')
    add(f'{sta_name}\n')
    add('*--- output files\n')
    add(f'./hypoDD_{suffix}.loc\n')
    add(f'./hypoDD_{suffix}.reloc\n')
    add(f'./hypoDD_{suffix}.sta\n')
    add(f'./hypoDD_{suffix}.res\n')
    add(f'./hypoDD_{suffix}.src\n')
    add('*--- IDAT IPHA MAXDIST (0=syn;1=cc;2=cat;3=both / 1=P,2=S,3=P&S)\n')
    add(f'  {idata}     {cfg.hypodd_iphase}     {cfg.hypodd_maxdist:g}\n')
    add('*--- OBSCC OBSCT\n')
    add(f'     {cfg.hypodd_minobs_cc}     {cfg.hypodd_minobs_ct}\n')
    nset = len(cfg.hypodd_iter_rows)
    add('*--- ISTART ISOLV NSET\n')
    add(f'    {cfg.hypodd_istart}        {cfg.hypodd_isolv}      {nset}\n')
    add('*--- NITER WTCCP WTCCS WRCC WDCC WTCTP WTCTS WRCT WDCT DAMP\n')
    for row in cfg.hypodd_iter_rows:
        niter = int(row[0])
        rest = row[1:]
        add(
            f'  {niter}   {rest[0]:g}   {rest[1]:g}   {rest[2]:g}   {rest[3]:g}   '
            f'{rest[4]:g}   {rest[5]:g}   {rest[6]:g}   {rest[7]:g}   {rest[8]:g}\n'
        )
    mod_nl = len(cfg.hypodd_mod_top)
    add('*--- NLAY RATIO\n')
    add(f'   {mod_nl}     {cfg.hypodd_mod_ratio:g}\n')
    add('*--- layer tops (km)\n')
    add(_fmt_layer_line(cfg.hypodd_mod_top))
    add('*--- layer Vp (km/s)\n')
    add(_fmt_layer_line(cfg.hypodd_mod_vel))
    add('*--- CID (0=all clusters)\n')
    add(f'    {cfg.hypodd_iclust}\n')

    out_path = os.path.join(out_folder, f'hypoDD_{i}-{j}.inp')
    with open(out_path, 'w') as fout:
        fout.writelines(lines)


def _write_hypodd_inp_from_template(i, j, out_folder, cfg):
    """Legacy path and filename substitution on template lines.

    Parameters
    ----------
    i, j : int
        Grid indices for ``dt``, ``event``, and ``hypoDD`` output names.
    out_folder : str
        Output directory for ``hypoDD_{i}-{j}.inp``.
    cfg : object
        Must provide ``hypoDD_inp_template`` and ``hypodd_dt_cc_per_grid``.
    """
    fout = open(os.path.join(out_folder, f'hypoDD_{i}-{j}.inp'), 'w')
    with open(cfg.hypoDD_inp_template) as f:
        lines = f.readlines()
    cc_path = f'./dt_{i}-{j}.cc\n' if getattr(cfg, 'hypodd_dt_cc_per_grid', True) else './dt.cc\n'
    for line in lines:
        if 'dt.cc' in line:
            line = cc_path
        if 'dt.ct' in line:
            line = f'./dt_{i}-{j}.ct \n'
        if 'event.dat' in line:
            line = f'./event_{i}-{j}.dat \n'
        if 'station.dat' in line:
            line = './hypoDD_station.dat \n'
        if 'hypoDD.loc' in line:
            line = f'./hypoDD_{i}-{j}.loc \n'
        if 'hypoDD.reloc' in line:
            line = f'./hypoDD_{i}-{j}.reloc \n'
        if 'hypoDD.sta' in line:
            line = f'./hypoDD_{i}-{j}.sta \n'
        if 'hypoDD.res' in line:
            line = f'./hypoDD_{i}-{j}.res \n'
        if 'hypoDD.src' in line:
            line = f'./hypoDD_{i}-{j}.src \n'
        fout.write(line)
    fout.close()


def write_hypodd_inp(i, j, out_folder, cfg):
    """
    Write hypoDD input file for a given grid.

    Uses cfg.hypodd_inp_mode: 'programmatic' (default) or 'template'.

    Parameters
    ----------
    i, j : int
        Grid indices.
    out_folder : str
        Working directory for this grid's ``hypoDD_*.inp``.
    cfg : object
        See :func:`write_hypodd_inp_programmatic` / ``hypodd_inp_mode``.
    """
    mode = getattr(cfg, 'hypodd_inp_mode', 'programmatic')
    if mode == 'template':
        _write_hypodd_inp_from_template(i, j, out_folder, cfg)
    else:
        write_hypodd_inp_programmatic(i, j, out_folder, cfg)

class Run_HypoDD(Dataset):
    """
    Internal Dataset wrapper for running the native HypoDD binary per grid.

    This class is used by ``run_hypodd_pipeline`` after station/phase files,
    ``ph2dt`` outputs, and optional ``dt.cc`` files have been prepared. Generated
    task scripts should not instantiate it directly for normal relocation.

    Parameters
    ----------
    evid_lists : list of list
        Nested list mapping grid index to event IDs.
    idx_list : list of tuple
        List of grid indices (i, j) to process.
    pha_dict : dict
        Dictionary mapping event ID to phase pick lines.
    mag_dict : dict
        Dictionary mapping event ID to event magnitude.
    out_folder : str
        Directory for all outputs.
    cfg : object
        Config with:
            - dep_corr (float): depth correction (km).
            - ctlg_code (str): prefix for output catalog/phase files.
            - hypoDD_exe (str): path to the HypoDD binary (``hypo_root/hypoDD``).
            - hypodd_inp_mode, hypodd_idata, hypodd_dt_cc_per_grid: see :func:`write_hypodd_inp`.
              When ``hypodd_idata`` is 1 or 3, place ``dt_{i}-{j}.cc`` in ``out_folder`` (or
              ``./dt.cc`` if ``hypodd_dt_cc_per_grid`` is False).

    Notes
    -----
    - Each grid run writes `ctlg`, `pha`, and `pha_full` files with relocated
      event information and phase picks.
    - Calls :func:`write_hypodd_inp` to generate HypoDD control files.
    - Executes the native HypoDD binary through an internal subprocess call.
    """
    def __init__(self, evid_lists, idx_list, pha_dict, mag_dict, out_folder, cfg):
        self.cfg          = cfg
        self.idx_list     = idx_list
        self.evid_lists   = evid_lists
        self.pha_dict     = pha_dict
        self.mag_dict     = mag_dict
        self.out_folder   = out_folder
        self.dep_corr     = cfg.dep_corr
        self.ctlg_code    = cfg.ctlg_code
        self.hypoDD_exe   = cfg.hypoDD_exe

    def __getitem__(self, index):
        """Execute HypoDD for one grid, writing grid-wise ``.loc``, ``.reloc``, and ``.pha``.

        Parameters
        ----------
        index : int
            Index into ``self.idx_list`` selecting the ``(i, j)`` grid.
        """
        # i/o paths
        i, j = self.idx_list[index]
        evid_list    = self.evid_lists[i][j]
        write_hypodd_inp(i,j, self.out_folder, self.cfg)
        # ``cfg.hypoDD_exe`` is already the full path to the ``hypoDD`` binary
        # (``os.path.join(hypo_root, "hypoDD")``), not a directory.
        log_path = os.path.join(self.out_folder, f"{i}-{j}.hypoDD")
        run_native_program(
            [self.hypoDD_exe, f"hypoDD_{i}-{j}.inp"],
            cwd=self.out_folder,
            log_path=log_path,
            program=f"hypoDD grid {i}-{j}",
        )

        # format loc output
        floc = os.path.join(self.out_folder, f'hypoDD_{i}-{j}.loc')
        if not os.path.isfile(floc):
            log_tail = read_log_tail(log_path, max_lines=40)
            if "# dtimes total =        0" in log_tail or "# dtimes total = 0" in log_tail:
                raise InsufficientDTimeError(
                    "HypoDD could not relocate this selected window because no "
                    "differential-time observations were available after ph2dt/HypoDD "
                    "selection (# dtimes total = 0). This usually means the window "
                    "is too sparse, event links are too weak, or ph2dt pair constraints "
                    "are too strict. Merge this time window with a neighboring window, "
                    "increase the selected event/link density, or relax ph2dt pairing "
                    "parameters. Do not treat this as a phase-file format error.\n"
                    f"Expected loc file: {floc}\n"
                    f"HypoDD log: {log_path}\n"
                    f"--- log tail ---\n{log_tail}"
                )
            if (
                "# clusters:    0" in log_tail
                or "# clusters: 0" in log_tail
                or "Clustered events:     0" in log_tail
                or "Clustered events: 0" in log_tail
            ):
                raise InsufficientDTimeError(
                    "HypoDD could not relocate this selected window because "
                    "the available differential-time observations did not form "
                    "any relocatable clusters. In CC-only mode this usually "
                    "means FDTCC produced too few usable dt.cc links for the "
                    "selected events/stations. Merge this window with adjacent "
                    "events, select a denser event window, relax FDTCC/CC "
                    "thresholds carefully, or use catalog+CC mode if catalog "
                    "differential times should contribute.\n"
                    f"Expected loc file: {floc}\n"
                    f"HypoDD log: {log_path}\n"
                    f"--- log tail ---\n{log_tail}"
                )
            hints = []
            if "Increase MAXEVE" in log_tail:
                hints.append(
                    "HypoDD stopped because the number of events exceeded MAXEVE "
                    "in hypoDD.inc. For catalog-only large runs, prefer "
                    "run_catalog_only_auto_time_windows(...), or otherwise use an "
                    "explicit package-supported split so each native window is "
                    "<= MAXEVE. Rebuilding native HypoDD with a larger MAXEVE is "
                    "a separate maintenance task."
                )
            if "Increase MAXDATA" in log_tail:
                hints.append(
                    "HypoDD stopped because the number of differential-time data "
                    "exceeded MAXDATA in hypoDD.inc. Reduce ph2dt link density "
                    "or use package-supported time/event windows. Rebuilding "
                    "native HypoDD with a larger MAXDATA is a separate maintenance task."
                )
            if "Increase MAXCL" in log_tail:
                hints.append(
                    "HypoDD stopped because the number of clusters exceeded MAXCL "
                    "in hypoDD.inc. Reduce the event-window size, improve "
                    "event-pair connectivity, or increase MAXCL and rebuild HypoDD."
                )
            hint = (" " + " ".join(hints)) if hints else ""
            raise RuntimeError(
                f"HypoDD did not create expected loc file: {floc}.{hint}\n"
                f"HypoDD log: {log_path}\n"
                f"--- log tail ---\n{log_tail}"
            )
        f=open(floc); lines=f.readlines(); f.close()
        out_loc = open(os.path.join(self.out_folder, f'{self.ctlg_code}_{i}-{j}.loc'),'w')
        for line in lines:
            codes = line.split()
            evid = codes[0]
            if int(evid) not in evid_list: continue
            mag = self.mag_dict[evid]
            # get loc info
            lat, lon, dep = codes[1:4]
            dep = round(float(dep) - self.dep_corr, 2)
            # get time info
            year, mon, day, hour, mnt, sec = codes[10:16]
            sec = '59.99' if sec=='60.00' else sec
            ot = UTCDateTime(f"{year}{mon.zfill(2)}{day.zfill(2)}{hour.zfill(2)}{mnt.zfill(2)}{float(sec):.6f}")
            out_loc.write(f'{ot},{lat},{lon},{dep},{mag}\n')
        out_loc.close()

        # format reloc output
        freloc = os.path.join(self.out_folder, f'hypoDD_{i}-{j}.reloc')
        if not os.path.exists(freloc): return
        f=open(freloc); lines=f.readlines(); f.close()
        out_reloc = open(os.path.join(self.out_folder, f'{self.ctlg_code}_{i}-{j}.reloc'),'w')
        out_pha = open(os.path.join(self.out_folder, f'{self.ctlg_code}_{i}-{j}.pha'),'w')
        for line in lines:
            codes = line.split()
            evid = codes[0]
            if int(evid) not in evid_list: continue
            pha_lines = self.pha_dict[evid]
            mag = self.mag_dict[evid]
            # get loc info
            lat, lon, dep = codes[1:4]
            dep = round(float(dep) - self.dep_corr, 2)
            # get time info
            year, mon, day, hour, mnt, sec = codes[10:16]
            sec = '59.999' if sec=='60.000' else sec
            ot = UTCDateTime(f"{year}{mon.zfill(2)}{day.zfill(2)}{hour.zfill(2)}{mnt.zfill(2)}{float(sec):.6f}")
            out_reloc.write(f'{ot},{lat},{lon},{dep},{mag}\n')
            out_pha.write(f'{ot},{lat},{lon},{dep},{mag},{evid}\n')
            for pha_line in pha_lines:
                out_pha.write(pha_line)
        out_reloc.close()
        out_pha.close()

    def __len__(self):
        """Number of (i, j) grids in ``idx_list``.

        Returns
        -------
        int
            ``len(self.idx_list)``.
        """
        return len(self.idx_list)


def merge_hypodd_residual_files(output_folder: str, ctlg_code: str) -> None:
    """Merge per-grid residual files into ``{ctlg_code}.res``.

    Parameters
    ----------
    output_folder
        Directory containing native ``hypoDD_{i}-{j}.res`` files.
    ctlg_code
        Catalog prefix for the merged residual file.

    Notes
    -----
    The merged file keeps one residual table header. Missing per-grid residual
    files are tolerated; this helper does not by itself prove relocation
    success.
    """
    pattern = os.path.join(output_folder, "hypoDD_[0-9]*-[0-9].res")
    paths = sorted(glob.glob(pattern))
    if not paths:
        return
    out_path = os.path.join(output_folder, f"{ctlg_code}.res")
    with open(out_path, "w", encoding="utf-8") as fout:
        for i, p in enumerate(paths):
            with open(p, "r", encoding="utf-8", errors="replace") as fin:
                lines = fin.readlines()
            if not lines:
                continue
            if i == 0:
                fout.writelines(lines)
            else:
                start = 1 if lines[0].lstrip().upper().startswith("STA") else 0
                fout.writelines(lines[start:])


def _concat_existing_files(pattern: str, out_path: str) -> None:
    """Concatenate files matching ``pattern`` into ``out_path`` if any exist."""
    paths = sorted(glob.glob(pattern))
    if not paths:
        return
    with open(out_path, "w", encoding="utf-8", errors="replace") as fout:
        for path in paths:
            with open(path, "r", encoding="utf-8", errors="replace") as fin:
                shutil.copyfileobj(fin, fout)


def merge_hypodd_output(ctlg_code, output_folder, keep_grids=False):
    """
    Merge grid-wise products; ``keep_grids`` controls HypoDD intermediates only.

    Always merged when present: ``{ctlg}.loc``, ``{ctlg}.reloc``, ``{ctlg}.pha``,
    ``{ctlg}.res``, logs. **Never deleted:** ``dt_*.ct``, ``dt_*.cc``.

    If ``keep_grids`` is False, removes per-grid ``hypoDD_*.*`` including
    ``.reloc.001.NNN`` snapshots, after merging.

    Parameters
    ----------
    ctlg_code : str
        Catalog prefix; merged files are named ``{ctlg_code}.loc`` etc.
    output_folder : str
        Directory containing per-grid HypoDD and ph2dt outputs.
    keep_grids : bool, optional
        If False, delete per-grid intermediates after concatenation (default False).
    """
    _concat_existing_files(
        os.path.join(output_folder, f"{ctlg_code}_[0-9]*-[0-9].loc"),
        os.path.join(output_folder, f"{ctlg_code}.loc"),
    )
    _concat_existing_files(
        os.path.join(output_folder, f"{ctlg_code}_[0-9]*-[0-9].reloc"),
        os.path.join(output_folder, f"{ctlg_code}.reloc"),
    )
    _concat_existing_files(
        os.path.join(output_folder, f"{ctlg_code}_[0-9]*-*[0-9].pha"),
        os.path.join(output_folder, f"{ctlg_code}.pha"),
    )
    _concat_existing_files(
        os.path.join(output_folder, "[0-9]*-[0-9].ph2dt"),
        os.path.join(output_folder, "ph2dt.log"),
    )
    _concat_existing_files(
        os.path.join(output_folder, "[0-9]*-[0-9].hypoDD"),
        os.path.join(output_folder, "hypoDD.log"),
    )
    merge_hypodd_residual_files(output_folder, ctlg_code)

    loc_grids = glob.glob(f"{output_folder}/hypoDD_[0-9]*-[0-9].loc*")
    loc_grids += glob.glob(f"{output_folder}/{ctlg_code}_[0-9]*-[0-9].loc*")
    reloc_grids = glob.glob(f"{output_folder}/hypoDD_[0-9]*-[0-9].reloc*")
    reloc_grids += glob.glob(f"{output_folder}/{ctlg_code}_[0-9]*-[0-9].reloc*")
    pha_grids = glob.glob(f"{output_folder}/{ctlg_code}_[0-9]*-[0-9]*.pha")
    res_grids = glob.glob(f"{output_folder}/hypoDD_[0-9]*-[0-9].res")

    output_files = glob.glob(f"{output_folder}/hypoDD_phase*.dat")
    output_files += glob.glob(f"{output_folder}/hypoDD_station*.dat")
    output_files += glob.glob(f"{output_folder}/event*.dat")
    output_files += glob.glob(f"{output_folder}/ph2dt*.inp")
    output_files += glob.glob(f"{output_folder}/[0-9]*-[0-9].ph2dt")
    output_files += glob.glob(f"{output_folder}/event.sel")
    output_files += glob.glob(f"{output_folder}/hypoDD_*.inp")
    output_files += glob.glob(f"{output_folder}/hypoDD*.src")
    output_files += glob.glob(f"{output_folder}/hypoDD*.sta")
    output_files += glob.glob(f"{output_folder}/[0-9]*-[0-9].hypoDD")

    if not keep_grids:
        for path in reloc_grids:
            try:
                os.unlink(path)
            except OSError:
                pass
        for path in loc_grids:
            try:
                os.unlink(path)
            except OSError:
                pass
        for path in pha_grids:
            try:
                os.unlink(path)
            except OSError:
                pass
        for path in res_grids:
            try:
                os.unlink(path)
            except OSError:
                pass
        for path in output_files:
            try:
                os.unlink(path)
            except OSError:
                pass
    return


def load_hypodd_residual_table(
    ctlg_code: str, output_folder: str
) -> Optional[pd.DataFrame]:
    """Load merged HypoDD residuals as a pandas DataFrame.

    Parameters
    ----------
    ctlg_code, output_folder
        Catalog prefix and directory containing ``{ctlg_code}.res``.

    Returns
    -------
    pandas.DataFrame or None
        Residual table with columns ``STA``, ``DT``, ``C1``, ``C2``, ``IDX``,
        ``QUAL``, ``RES_ms``, ``WT`` and ``OFFS``. Returns ``None`` when the
        merged residual file is absent or cannot be parsed.

    Notes
    -----
    Native HypoDD ``IDX`` values are: ``1`` CC P, ``2`` CC S, ``3`` catalog P,
    and ``4`` catalog S. ``RES_ms`` is already in milliseconds.
    """
    path = os.path.join(output_folder, f"{ctlg_code}.res")
    if not os.path.isfile(path):
        return None
    names = ["STA", "DT", "C1", "C2", "IDX", "QUAL", "RES_ms", "WT", "OFFS"]
    try:
        df = pd.read_csv(
            path,
            sep=r"\s+",
            skiprows=1,
            names=names,
            engine="python",
            comment="#",
        )
    except Exception:
        return None
    if df.empty:
        return df
    for col in ("DT", "QUAL", "RES_ms", "WT", "OFFS"):
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")
    for col in ("C1", "C2", "IDX"):
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")
    return df


def plot_hypodd_run_summary(
    ctlg_code: str,
    output_folder: str,
    *,
    dep_down: bool = True,
    idx_labels={1: "CC P", 2: "CC S", 3: "cat P", 4: "cat S"},
) -> None:
    """Write compact diagnostic plots from merged HypoDD outputs.

    Parameters
    ----------
    ctlg_code, output_folder
        Catalog prefix and output directory containing merged ``.loc``,
        ``.reloc`` and optionally ``.res`` files.
    dep_down
        If true, plot depth as positive downward in cross sections.
    idx_labels
        Mapping from HypoDD residual ``IDX`` values to legend labels.

    Outputs
    -------
    None
        Writes ``{ctlg_code}_hypodd_maps.png`` and, when residuals exist,
        ``{ctlg_code}_residuals.png`` in ``output_folder``.

    Notes
    -----
    These plots are diagnostics, not success criteria. Validate native output
    files and run manifests before reporting scientific success.
    """
    import matplotlib.pyplot as plt
    import matplotlib.dates as mdates

    orig = load_hypodd_original_catalog(ctlg_code, output_folder)
    reloc = load_hypodd_reloc_catalog(ctlg_code, output_folder)

    fig, axes = plt.subplots(2, 2, figsize=(11, 10), constrained_layout=True)

    ax = axes[0, 0]
    ax.scatter(orig["lon"], orig["lat"], c="indianred", s=12, alpha=0.7, label="original")
    ax.scatter(reloc["lon"], reloc["lat"], c="steelblue", s=12, alpha=0.7, label="reloc")
    ax.set_xlabel("Lon")
    ax.set_ylabel("Lat")
    ax.set_title("Map view")
    ax.legend(loc="best")
    ax.set_aspect("equal", adjustable="box")

    dep_o = orig["dep"].astype(float)
    dep_r = reloc["dep"].astype(float)
    if dep_down:
        dep_o = -dep_o
        dep_r = -dep_r
    ax = axes[0, 1]
    ax.scatter(orig["lon"], dep_o, c="indianred", s=12, alpha=0.7, label="original")
    ax.scatter(reloc["lon"], dep_r, c="steelblue", s=12, alpha=0.7, label="reloc")
    ax.set_xlabel("Lon")
    ylab = "Depth (km, positive down)" if dep_down else "Depth (km)"
    ax.set_ylabel(ylab)
    ax.set_title("Lon–depth")
    ax.legend(loc="best")

    ax = axes[1, 0]
    ax.scatter(orig["lat"], dep_o, c="indianred", s=12, alpha=0.7, label="original")
    ax.scatter(reloc["lat"], dep_r, c="steelblue", s=12, alpha=0.7, label="reloc")
    ax.set_xlabel("Lat")
    ax.set_ylabel(ylab)
    ax.set_title("Lat–depth")
    ax.legend(loc="best")

    ax = axes[1, 1]
    ot_r = reloc["ot"].apply(lambda x: mdates.date2num(UTCDateTime(x)))
    mag_r = reloc["mag"].astype(float)
    ax.scatter(ot_r, mag_r, c="steelblue", s=18, alpha=0.75)
    ax.set_xlabel("Origin time")
    ax.set_ylabel("Magnitude")
    ax.set_title("Time–magnitude (reloc)")
    ax.xaxis_date()
    fig.autofmt_xdate()

    fig.suptitle(f"{ctlg_code}: HypoDD relocation overview", fontsize=13)
    plt.savefig(os.path.join(output_folder, f"{ctlg_code}_hypodd_maps.png"), dpi=150)
    plt.close(fig)

    res_df = load_hypodd_residual_table(ctlg_code, output_folder)
    fig2, ax2 = plt.subplots(figsize=(9, 5.5), constrained_layout=True)
    if res_df is None or res_df.empty or "RES_ms" not in res_df.columns:
        ax2.text(0.5, 0.5, "No residual table (.res)", ha="center", va="center")
        ax2.set_axis_off()
    else:
        valid = res_df.dropna(subset=["RES_ms", "IDX"])
        idx_vals = sorted(int(x) for x in valid["IDX"].dropna().unique())
        colors = plt.cm.tab10.colors
        for k, ix in enumerate(idx_vals):
            sub = valid[valid["IDX"] == ix]["RES_ms"]
            if sub.empty:
                continue
            label = idx_labels.get(ix, f"IDX {ix}")
            ax2.hist(
                sub,
                bins=60,
                alpha=0.45,
                label=f"{label} (n={len(sub)})",
                color=colors[k % len(colors)],
                density=True,
            )
        ax2.set_xlabel("Residual (ms)")
        ax2.set_ylabel("Density")
        ax2.set_title(f"{ctlg_code}: HypoDD differential-time residuals")
        ax2.legend(loc="best", fontsize=9)
    plt.savefig(os.path.join(output_folder, f"{ctlg_code}_residuals.png"), dpi=150)
    plt.close(fig2)


def _native_log_candidates(output_folder):
    patterns = (
        "*.log",
        "*.err",
        "*.out",
        "*.stderr",
        "hypoDD*",
        "ph2dt*",
    )
    hits = []
    for pat in patterns:
        hits.extend(glob.glob(os.path.join(output_folder, pat)))
    hits = sorted({p for p in hits if os.path.isfile(p)})
    return hits[:8]


def _read_merged_hypodd_catalog(ctlg_code, output_folder, suffix, label):
    ctlg_file = os.path.join(output_folder, f"{ctlg_code}.{suffix}")
    logs = _native_log_candidates(output_folder)
    log_hint = ", ".join(os.path.basename(p) for p in logs) if logs else "no log-like files found"
    evidence_hint = (
        "Inspect native evidence in this same output directory before changing "
        "parameters or inputs: hypoDD/ph2dt logs, hypoDD_*-*.inp, dt_*.ct, "
        "hypoDD_phase_*.dat, hypoDD_*.loc, hypoDD_*.reloc, hypoDD_*.src, "
        "and hypoDD_*.sta. Do not infer MAXEVE/MAXDATA, reduce events, alter "
        "phase parsing, or tune ph2dt/HypoDD parameters from this message alone; "
        "use the native log text as the cause."
    )
    if not os.path.exists(ctlg_file):
        raise NativeOutputError(
            f"Missing HypoDD native {label} catalog: {ctlg_file}. "
            "This file must be produced by the ph2dt/HypoDD pipeline; do not "
            f"create {ctlg_code}.csv as a substitute. Native evidence candidates: "
            f"{log_hint}. {evidence_hint}"
        )
    if os.path.getsize(ctlg_file) == 0:
        raise NativeOutputError(
            f"Empty HypoDD native {label} catalog: {ctlg_file}. "
            "HypoDD produced the expected catalog path but no valid catalog rows. "
            "This is a native-output failure, not by itself a config/schema error "
            "or an event-count-limit error. Do not treat placeholder CSV files as "
            f"success. Native evidence candidates: {log_hint}. {evidence_hint}"
        )
    try:
        catalog = pd.read_csv(ctlg_file, sep=",", header=None)
    except pd.errors.EmptyDataError as exc:
        raise NativeOutputError(
            f"HypoDD native {label} catalog has no parseable rows: {ctlg_file}. "
            "HypoDD produced a catalog file but it contains no parseable rows. "
            "This message alone does not identify the scientific/native cause. "
            f"Native evidence candidates: {log_hint}. {evidence_hint}"
        ) from exc
    if catalog.empty or catalog.shape[1] < 5:
        raise NativeOutputError(
            f"HypoDD native {label} catalog is invalid: {ctlg_file}; "
            f"rows={len(catalog)}, columns={catalog.shape[1]}. Expected at least "
            "five columns: ot, lat, lon, dep, mag. This message only reports "
            "invalid native output shape; inspect the native evidence to determine "
            f"the cause. Native evidence candidates: {log_hint}. {evidence_hint}"
        )
    catalog = catalog.iloc[:, :5].copy()
    catalog.columns = ["ot", "lat", "lon", "dep", "mag"]
    catalog["ot"] = catalog["ot"].apply(lambda x: UTCDateTime(x))
    catalog["lat"] = catalog["lat"].apply(lambda x: float(x))
    catalog["lon"] = catalog["lon"].apply(lambda x: float(x))
    catalog["dep"] = catalog["dep"].apply(lambda x: float(x))
    catalog["mag"] = catalog["mag"].apply(lambda x: float(x))
    return catalog


def load_hypodd_original_catalog(ctlg_code, output_folder):
    """
    Load hypoDD output files (raw location catalog).
    
    Parameters
    ----------
    ctlg_code : str
        Prefix for output catalog/phase files.
    output_folder : str
        Directory containing the merged ``{ctlg_code}.loc`` file.
        
    Returns
    -------
    catalog : pandas.DataFrame
        Catalog dataframe with columns: 'ot', 'lat', 'lon', 'dep', 'mag'.
        
    """
    return _read_merged_hypodd_catalog(ctlg_code, output_folder, "loc", "original")

def load_hypodd_reloc_catalog(ctlg_code, output_folder):
    """
    Load hypoDD output files (relocated catalog).
    
    Parameters
    ----------
    ctlg_code : str
        Prefix for output catalog/phase files.
    output_folder : str
        Directory containing the merged ``{ctlg_code}.reloc`` file.
        
    Returns
    -------
    catalog : pandas.DataFrame
        Catalog dataframe with columns: 'ot', 'lat', 'lon', 'dep', 'mag'.
        
    """
    return _read_merged_hypodd_catalog(ctlg_code, output_folder, "reloc", "relocated")
