#!/usr/bin/env python3
"""Audit official MinerU outputs without submitting new parsing jobs.

The audit deliberately treats the original PDF as the source of truth and
checks whether a successful MinerU task left enough local structure for
traceable scientific extraction: model pages, content-list pages, tables,
images, OCR replacement characters, and a stable Markdown derivative.
"""
from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from pathlib import Path


IMAGE_RE = re.compile(r"!\[[^]]*\]\(([^)]+)\)")


def walk_types(value, counts: Counter[str]) -> None:
    if isinstance(value, dict):
        kind = value.get("type")
        if isinstance(kind, str):
            counts[kind] += 1
        for item in value.values():
            walk_types(item, counts)
    elif isinstance(value, list):
        for item in value:
            walk_types(item, counts)


def latest_summary(folder: Path) -> dict | None:
    files = sorted(folder.glob("processing_summary_*.json"))
    if not files:
        return None
    try:
        return json.loads(files[-1].read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def audit_pdf(pdf: Path) -> dict:
    paper_dir = pdf.parent
    parsed_dir = paper_dir.parent / "parsed" / "paper"
    out_dir = parsed_dir / "mineru" / pdf.stem
    full = out_dir / "full.md"
    if not full.exists():
        candidates = sorted(out_dir.rglob("*.md")) if out_dir.is_dir() else []
        full = candidates[0] if candidates else None

    summary = latest_summary(parsed_dir / "mineru")
    status = "unknown"
    errors = []
    if summary:
        status = "success" if summary.get("successful", 0) == 1 else "failed"
        errors = summary.get("errors", [])
    text = full.read_text(encoding="utf-8", errors="replace") if full else ""

    model_files = sorted(out_dir.glob("*_model.json")) if out_dir.is_dir() else []
    model_pages = None
    type_counts: Counter[str] = Counter()
    if model_files:
        try:
            model = json.loads(model_files[-1].read_text(encoding="utf-8"))
            model_pages = len(model) if isinstance(model, list) else None
            walk_types(model, type_counts)
        except (OSError, json.JSONDecodeError):
            pass

    content_files = sorted(out_dir.glob("*_content_list_v2.json")) if out_dir.is_dir() else []
    content_pages = None
    if content_files:
        try:
            content = json.loads(content_files[-1].read_text(encoding="utf-8"))
            content_pages = len(content) if isinstance(content, list) else None
        except (OSError, json.JSONDecodeError):
            pass

    image_refs = IMAGE_RE.findall(text)
    missing_images = []
    for ref in image_refs:
        if ref.startswith(("http://", "https://", "data:")):
            continue
        if not full or not (full.parent / ref).exists():
            missing_images.append(ref)

    return {
        "case_id": pdf.parents[3].name,
        "source_id": pdf.parents[1].name,
        "pdf": str(pdf),
        "status": status,
        "errors": errors,
        "full_markdown": str(full) if full else None,
        "stable_markdown": str(parsed_dir / f"{pdf.stem}__mineru.md"),
        "stable_markdown_exists": (parsed_dir / f"{pdf.stem}__mineru.md").exists(),
        "chars": len(text),
        "lines": text.count("\n") + 1 if text else 0,
        "replacement_chars": text.count("\ufffd"),
        "model_pages": model_pages,
        "content_list_pages": content_pages,
        "model_types": dict(sorted(type_counts.items())),
        "html_tables": len(re.findall(r"<table\b", text, re.I)),
        "image_refs": len(image_refs),
        "missing_image_refs": missing_images,
    }


def discover(root: Path) -> list[Path]:
    return sorted(root.glob("data/*/references/*/paper/*.pdf"))


def markdown_report(records: list[dict]) -> str:
    total = len(records)
    success = sum(r["status"] == "success" for r in records)
    stable = sum(r["stable_markdown_exists"] for r in records)
    failed = [r for r in records if r["status"] != "success"]
    replacement = [r for r in records if r["replacement_chars"]]
    missing_images = [r for r in records if r["missing_image_refs"]]

    lines = [
        "# MinerU paper parsing audit",
        "",
        "> Generated by `scripts/01_pdf_parsing/audit_mineru_outputs.py`. This is",
        "> an output audit, not a substitute for reading the source PDF.",
        "",
        "## Coverage",
        "",
        f"- Paper PDFs discovered: **{total}**",
        f"- Successful MinerU tasks: **{success}**",
        f"- Failed or unresolved tasks: **{total - success}**",
        f"- Stable `parsed/paper/*__mineru.md` derivatives present: **{stable}/{total}**",
        f"- Outputs with Unicode replacement characters: **{len(replacement)}**",
        f"- Outputs with missing image references: **{len(missing_images)}**",
        "",
        "## Per-paper audit",
        "",
        "| Case | Source | Status | Model pages | Content pages | Characters | Tables | Images | Replacement chars | Stable Markdown |",
        "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for r in records:
        types = r["model_types"]
        table_count = types.get("table", 0) or r["html_tables"]
        lines.append(
            "| {case_id} | {source_id} | {status} | {model_pages} | {content_list_pages} | "
            "{chars} | {tables} | {image_refs} | {replacement_chars} | {stable} |".format(
                tables=table_count,
                stable="yes" if r["stable_markdown_exists"] else "no",
                **r,
            )
        )

    lines += ["", "## Interpretation", ""]
    lines += [
        "- The successful outputs preserve substantial text and visual assets. HTML tables are present in the Markdown where MinerU detected tables; downstream extraction must parse HTML tables rather than assume GitHub pipe tables.",
        "- The Markdown concatenation does not preserve explicit PDF page boundaries. Quantitative claims therefore require an evidence anchor from the source PDF or the page-indexed `*_model.json`/`*_content_list_v2.json` artifacts.",
        "- Unicode replacement characters indicate OCR or encoding uncertainty. Those passages require visual confirmation before recording exact symbols, signs, units, or numbers.",
        "- A successful parse is necessary but not sufficient for benchmark extraction: the paper reading record still has to distinguish article-reported catalog counts from local-file audits and identify the catalog lineage.",
        "- `MAPLE_RELATED_OPEN` is a related open article about the Sheldon, Nevada sequence, not evidence for the Maple Creek/Yellowstone catalog; keep it as context only.",
        "- The two `QUAKEFLOW_GJI_GGAC355` PDFs have different roles: the 10-page article is method context, while the 62-page evaluation deck is QC/context and not a Kīlauea event-catalog release.",
        "- This wrapper discovers only `paper/*.pdf`; supplementary PDF/DOCX/XLSX/XML products are intentionally outside this audit and must be checked separately because they may contain the catalog schema and thresholds.",
    ]
    if failed:
        lines += ["", "## Failed or unresolved outputs", ""]
        for r in failed:
            lines.append(f"- `{r['case_id']}/{r['source_id']}`: {r['errors'] or 'no successful summary'}")
    if replacement:
        lines += ["", "## OCR/encoding review queue", ""]
        for r in replacement:
            lines.append(f"- `{r['case_id']}/{r['source_id']}`: {r['replacement_chars']} replacement characters")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--report", type=Path, help="Write a Markdown audit report")
    parser.add_argument("--json", dest="json_path", type=Path, help="Write machine-readable audit JSON")
    args = parser.parse_args()

    records = [audit_pdf(pdf) for pdf in discover(args.root)]
    report = markdown_report(records)
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(report, encoding="utf-8")
    if args.json_path:
        args.json_path.parent.mkdir(parents=True, exist_ok=True)
        args.json_path.write_text(json.dumps(records, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if not args.report:
        print(report, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
