"""Internal ph2dt driver used by the relocation pipeline.

This module writes ``ph2dt.inp``, runs the native ``ph2dt`` binary per grid, and
renames ``dt.ct`` / ``event.dat`` outputs. Generated task scripts should call
the public ``hypodd_runner`` function APIs instead of calling this module
directly.
"""
import os, shutil

try:
    from .native import run_native_program
    from .pha_format import looks_like_event_header_line, normalize_event_magnitude
except ImportError:  # pragma: no cover - legacy direct-script execution
    from native import run_native_program
    from pha_format import looks_like_event_header_line, normalize_event_magnitude


def write_ph2dt_inp(out_folder, cfg):
    """
    Write ph2dt.inp using the 3 non-comment lines expected by ph2dt.f
    (station file, phase file, then MINWGHT MAXDIST MAXSEP MAXNGH MINLNK MINOBS MAXOBS).

    Parameters
    ----------
    out_folder : str
        Working directory where ``ph2dt.inp`` is written. The generated input
        references ``./hypoDD_station.dat`` and ``./hypoDD_phase.dat`` in this
        same directory.
    cfg : object
        Config-like object with ``ph2dt_minwght``, ``ph2dt_maxdist``,
        ``ph2dt_maxoffset``, ``ph2dt_mnb``, ``ph2dt_limobs_pair``,
        ``ph2dt_minobs_pair``, and ``ph2dt_maxobs_pair`` attributes.
    """
    lines = [
        '* ph2dt.inp generated by hypodd\n',
        '* station file\n',
        './hypoDD_station.dat\n',
        '* phase file\n',
        './hypoDD_phase.dat\n',
        '* MINWGHT MAXDIST MAXSEP MAXNGH MINLNK MINOBS MAXOBS\n',
        f'   {cfg.ph2dt_minwght:g}      {cfg.ph2dt_maxdist:g}      '
        f'{cfg.ph2dt_maxoffset:g}     {cfg.ph2dt_mnb}      '
        f'{cfg.ph2dt_limobs_pair}      {cfg.ph2dt_minobs_pair}     '
        f'{cfg.ph2dt_maxobs_pair}\n',
    ]
    path = os.path.join(out_folder, 'ph2dt.inp')
    with open(path, 'w') as f:
        f.writelines(lines)


def _write_ph2dt_inp_from_template(out_folder, cfg):
    """Populate ``ph2dt.inp`` from ``cfg.hypoDD_ph2dt_template``, wiring HypoDD station/phase paths.

    Parameters
    ----------
    out_folder : str
        Working directory; ``ph2dt.inp`` is written here.
    cfg : object
        Must provide ``hypoDD_ph2dt_template`` for line substitution.
    """
    new_lines = []
    for line in open(cfg.hypoDD_ph2dt_template, 'r').readlines():
        if 'station.dat' in line:
            line = './hypoDD_station.dat \n'
        elif 'phase.dat' in line:
            line = './hypoDD_phase.dat \n'
        new_lines.append(line)
    with open(os.path.join(out_folder, 'ph2dt.inp'), 'w') as f:
        f.writelines(new_lines)

def read_fpha(pha_file):
    """
    Read a full phase file and organize phases by event ID.

    Parameters
    ----------
    pha_file : str
        Path to the phase file. Each event should start with a header line
        containing ``origin_time, lat, lon, depth, mag[, evid]`` (comma-separated).
        ``origin_time`` may be ``YYYYMMDDHHMMSS.SS`` or ISO-8601 (e.g. ``2019-07-04T16:13:43.220000Z``).
        ``lat``, ``lon``, and ``depth`` must be numeric; ``mag`` is filled as
        ``0.0`` when missing/bad. ``evid`` may be omitted and then assigned
        sequentially. Subsequent lines contain station picks for that
        event as ``station_id, ISO_P_pick, ISO_S_pick``. ``station_id`` may be
        ``NET.STA`` or a bare station code. Use ``-1``, ``nan``, ``None``,
        ``null``, ``NA``, or an empty field for a missing P or S pick. Extra
        columns are ignored by this parser and are not part of the required
        hypodd_runner input contract.
        The format of the phase file is as follows:
        ```
            20190704161343.44,35.7158,-117.5010,14.6,1.60,0
            CI.TOW2,2019-07-04T16:13:48.528000Z,2019-07-04T16:13:53.308000Z
            CI.SRT,2019-07-04T16:13:47.888000Z,-1
            ...
            20190704170255.38,35.7087,-117.5010,13.5,4.40,1
            CI.TOW2,2019-07-04T17:03:00.428000Z,2019-07-04T17:03:05.268000Z
            CI.SRT,-1,2019-07-04T17:03:03.888000Z
            ...
        ```

    Returns
    -------
    pha_dict : dict
        Dictionary mapping event ID (str) to a list of phase pick lines (str).
    mag_dict : dict
        Dictionary mapping event ID (str) to the event magnitude (float).

    Notes
    -----
    - Event headers are detected with :func:`pha_format.looks_like_event_header_line`
      (parsable origin time + numeric lat/lon/dep, with optional integer evid in
      the last field). Missing/bad magnitude values are filled with 0.0.
    - Event ID (evid) is taken from the last field when present; otherwise a
      sequential string key is assigned.
    - Station pick lines are all other lines following the event header 
      until the next event.

    Examples
    --------
    >>> pha_dict, mag_dict = read_fpha('eg_pal_hyp_full.pha')
    >>> pha_dict['1001']  # list of pick lines for event 1001
    >>> mag_dict['1001']  # magnitude of event 1001
    """
    pha_dict, mag_dict = {}, {}
    evid: str = ""
    auto_evid = 0
    f=open(pha_file); lines=f.readlines(); f.close()
    for line in lines:
        codes = line.split(',')
        if len(codes)==1: codes = line.split()
        if looks_like_event_header_line(codes):
            if len(codes) >= 6:
                evid = str(int(float(codes[-1].strip())))
            else:
                auto_evid += 1
                evid = str(auto_evid)
            pha_dict[evid] = []
            mag_dict[evid] = normalize_event_magnitude(codes[4])
        else:
            if not evid:
                continue
            pha_dict[evid].append(line)
    return pha_dict, mag_dict

def run_ph2dt(out_folder, cfg):
    """
    Internal per-grid ph2dt execution used by ``run_hypodd_pipeline``.

    Runs the native ``ph2dt`` binary for each grid and generates differential
    time files. Normal callers should use the public relocation API.

    Parameters
    ----------
    out_folder : str
        Directory to save modified inputs and outputs.
    cfg : object
        Config with:
            - num_grids (tuple[int, int]): grid numbers in x, y.
            - ph2dt_exe (str): path to ph2dt executable directory.
            - ph2dt_inp_mode (str): ``'programmatic'`` (default) or ``'template'``.
            - hypoDD_ph2dt_template (str): used when ``ph2dt_inp_mode=='template'``.
            - ph2dt_minwght, ph2dt_maxdist, ph2dt_maxoffset, ph2dt_mnb,
              ph2dt_limobs_pair, ph2dt_minobs_pair, ph2dt_maxobs_pair: ph2dt parameters.

    Outputs
    -------
    - dt_{i}-{j}.ct : differential times
    - event_{i}-{j}.dat : event catalog
    - {i}-{j}.ph2dt : run log
    """
    for i in range(cfg.num_grids[0]):
        for j in range(cfg.num_grids[1]):
            print(f'run ph2dt: grid {i}-{j}')
            # copy phase.dat to out_folder
            shutil.copy(os.path.join(out_folder, f'hypoDD_phase_{i}-{j}.dat'), os.path.join(out_folder, 'hypoDD_phase.dat'))
            if getattr(cfg, 'ph2dt_inp_mode', 'programmatic') == 'template':
                _write_ph2dt_inp_from_template(out_folder, cfg)
            else:
                write_ph2dt_inp(out_folder, cfg)

            # run ph2dt in out_folder
            ph2dt_bin = os.path.join(cfg.ph2dt_exe, "ph2dt")
            log_path = os.path.join(out_folder, f"{i}-{j}.ph2dt")
            run_native_program(
                [ph2dt_bin, "ph2dt.inp"],
                cwd=out_folder,
                log_path=log_path,
                program=f"ph2dt grid {i}-{j}",
            )
            
            # rename outputs if exist
            if os.path.exists(os.path.join(out_folder, 'dt.ct')):
                shutil.move(os.path.join(out_folder, 'dt.ct'),
                            os.path.join(out_folder, f'dt_{i}-{j}.ct'))
            if os.path.exists(os.path.join(out_folder, 'event.dat')):
                shutil.move(os.path.join(out_folder, 'event.dat'),
                            os.path.join(out_folder, f'event_{i}-{j}.dat'))

            # remove log if exist
            log_path = os.path.join(out_folder, 'ph2dt.log')
            if os.path.exists(log_path):
                os.unlink(log_path)
    return
